export const COUNTRY_TO_ISO2: Readonly<Record<string, string>> = {
  "United States": "US",
  Canada: "CA",
  Mexico: "MX",
  Brazil: "BR",
  Argentina: "AR",
  Colombia: "CO",
  Chile: "CL",
  Peru: "PE",
  France: "FR",
  Germany: "DE",
  "United Kingdom": "GB",
  Italy: "IT",
  Spain: "ES",
  Netherlands: "NL",
  Portugal: "PT",
  Sweden: "SE",
  Finland: "FI",
  Japan: "JP",
  "South Korea": "KR",
  China: "CN",
  Thailand: "TH",
  Singapore: "SG",
  Indonesia: "ID",
  Philippines: "PH",
  Malaysia: "MY",
}

export const COUNTRY_TO_ISO3: Readonly<Record<string, string>> = {
  US: "USA",
  CA: "CAN",
  MX: "MEX",
  BR: "BRA",
  AR: "ARG",
  CO: "COL",
  CL: "CHL",
  PE: "PER",
  FR: "FRA",
  DE: "DEU",
  GB: "GBR",
  IT: "ITA",
  ES: "ESP",
  NL: "NLD",
  PT: "PRT",
  SE: "SWE",
  FI: "FIN",
  JP: "JPN",
  KR: "KOR",
  CN: "CHN",
  TH: "THA",
  SG: "SGP",
  ID: "IDN",
  PH: "PHL",
  MY: "MYS",
}

export const COUNTRY_NAME_OVERRIDES: Readonly<Record<string, string>> = {
  Deutschland: "Germany",
  Italia: "Italy",
  España: "Spain",
  Brasil: "Brazil",
  日本: "Japan",
  한국: "South Korea",
  中国: "China",
}
