export const COUNTRY_TO_ISO2: Readonly<Record<string, string>> = {
  "United States": "US",
  Canada: "CA",
  Mexico: "MX",
  Brazil: "BR",
  Argentina: "AR",
  Colombia: "CO",
  Chile: "CL",
  Peru: "PE",
  Uruguay: "UY",
  Ecuador: "EC",
  Venezuela: "VE",
  Bolivia: "BO",
  Paraguay: "PY",
  "Costa Rica": "CR",
  Panama: "PA",
  "Dominican Republic": "DO",
  "Puerto Rico": "PR",
  Cuba: "CU",
  Guatemala: "GT",
  Honduras: "HN",
  "El Salvador": "SV",
  Nicaragua: "NI",
  France: "FR",
  Belgium: "BE",
  Netherlands: "NL",
  Luxembourg: "LU",
  Germany: "DE",
  Austria: "AT",
  Switzerland: "CH",
  "United Kingdom": "GB",
  Ireland: "IE",
  Spain: "ES",
  Portugal: "PT",
  Italy: "IT",
  Greece: "GR",
  Croatia: "HR",
  Slovenia: "SI",
  Serbia: "RS",
  "Bosnia and Herzegovina": "BA",
  Albania: "AL",
  "North Macedonia": "MK",
  Montenegro: "ME",
  Malta: "MT",
  Sweden: "SE",
  Finland: "FI",
  Norway: "NO",
  Denmark: "DK",
  Iceland: "IS",
  Poland: "PL",
  "Czech Republic": "CZ",
  Slovakia: "SK",
  Hungary: "HU",
  Romania: "RO",
  Bulgaria: "BG",
  Ukraine: "UA",
  Russia: "RU",
  Lithuania: "LT",
  Latvia: "LV",
  Estonia: "EE",
  Moldova: "MD",
  Belarus: "BY",
  Turkey: "TR",
  Cyprus: "CY",
  Japan: "JP",
  "South Korea": "KR",
  China: "CN",
  Thailand: "TH",
  Singapore: "SG",
  Indonesia: "ID",
  Philippines: "PH",
  Malaysia: "MY",
  Vietnam: "VN",
  Taiwan: "TW",
  "Hong Kong": "HK",
  India: "IN",
  Cambodia: "KH",
  Laos: "LA",
  Myanmar: "MM",
  Mongolia: "MN",
  Australia: "AU",
  "New Zealand": "NZ",
  Fiji: "FJ",
  "Papua New Guinea": "PG",
  UAE: "AE",
  "Saudi Arabia": "SA",
  Israel: "IL",
  Lebanon: "LB",
  Jordan: "JO",
  Egypt: "EG",
  Morocco: "MA",
  "South Africa": "ZA",
  Tunisia: "TN",
  Iran: "IR",
  Iraq: "IQ",
  Kuwait: "KW",
  Qatar: "QA",
  Bahrain: "BH",
  Oman: "OM",
  Algeria: "DZ",
  Nigeria: "NG",
  Kenya: "KE",
  Ethiopia: "ET",
  Ghana: "GH",
}

export const COUNTRY_TO_ISO3: Readonly<Record<string, string>> = {
  US: "USA",
  CA: "CAN",
  MX: "MEX",
  BR: "BRA",
  AR: "ARG",
  CO: "COL",
  CL: "CHL",
  PE: "PER",
  UY: "URY",
  EC: "ECU",
  VE: "VEN",
  BO: "BOL",
  PY: "PRY",
  CR: "CRI",
  PA: "PAN",
  DO: "DOM",
  PR: "PRI",
  CU: "CUB",
  GT: "GTM",
  HN: "HND",
  SV: "SLV",
  NI: "NIC",
  FR: "FRA",
  BE: "BEL",
  NL: "NLD",
  LU: "LUX",
  DE: "DEU",
  AT: "AUT",
  CH: "CHE",
  GB: "GBR",
  IE: "IRL",
  ES: "ESP",
  PT: "PRT",
  IT: "ITA",
  GR: "GRC",
  HR: "HRV",
  SI: "SVN",
  RS: "SRB",
  BA: "BIH",
  AL: "ALB",
  MK: "MKD",
  ME: "MNE",
  MT: "MLT",
  SE: "SWE",
  FI: "FIN",
  NO: "NOR",
  DK: "DNK",
  IS: "ISL",
  PL: "POL",
  CZ: "CZE",
  SK: "SVK",
  HU: "HUN",
  RO: "ROU",
  BG: "BGR",
  UA: "UKR",
  RU: "RUS",
  LT: "LTU",
  LV: "LVA",
  EE: "EST",
  MD: "MDA",
  BY: "BLR",
  TR: "TUR",
  CY: "CYP",
  JP: "JPN",
  KR: "KOR",
  CN: "CHN",
  TH: "THA",
  SG: "SGP",
  ID: "IDN",
  PH: "PHL",
  MY: "MYS",
  VN: "VNM",
  TW: "TWN",
  HK: "HKG",
  IN: "IND",
  KH: "KHM",
  LA: "LAO",
  MM: "MMR",
  MN: "MNG",
  AU: "AUS",
  NZ: "NZL",
  FJ: "FJI",
  PG: "PNG",
  AE: "ARE",
  SA: "SAU",
  IL: "ISR",
  LB: "LBN",
  JO: "JOR",
  EG: "EGY",
  MA: "MAR",
  ZA: "ZAF",
  TN: "TUN",
  IR: "IRN",
  IQ: "IRQ",
  KW: "KWT",
  QA: "QAT",
  BH: "BHR",
  OM: "OMN",
  DZ: "DZA",
  NG: "NGA",
  KE: "KEN",
  ET: "ETH",
  GH: "GHA",
}

export const COUNTRY_NAME_OVERRIDES: Readonly<Record<string, string>> = {
  Deutschland: "Germany",
  Italia: "Italy",
  España: "Spain",
  Brasil: "Brazil",
  日本: "Japan",
  한국: "South Korea",
  中国: "China",
}
