// Regenerated from /spots.json + /spot_spot_types.json by
// `pnpm db:regen-spots` (scripts/regen-spots-seed.ts).
// Do not edit by hand — re-run the generator instead.
//
// The `id` field is the slug for re-seed stability; the DB
// primary key is always `gen_random_uuid()`. Every row is
// seeded with `createdBy: null` — ownership is only assigned
// when a real Supabase admin creates or edits the spot through
// the dashboard.

import type { NewSpot } from "@/lib/repositories/types";
import type { SportDiscipline } from "@/types/sport-events";

const SKATE: readonly SportDiscipline[] = [
  "Skateboard",
  "Rollerblade",
  "Scooter",
  "BMX",
];

export const SOURCE_SPOTS: readonly NewSpot[] = [
  {
    id: "viga-skatepark",
    name: "VIGA SKATEPARK",
    city: "Envigado",
    citySlug: "envigado",
    address: "Avenida Las Vegas, Envigado",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlcJLMER-IHoCppmzrjbpVDcN1HI05CC6SyE_Pk06AtfqlXrXaVn8NWveZwMZ4ZbY2RipFausK47bnLRx3M50HPoFinp8K4SQ7-otFXjz6G1YdtBmXTvBKOK8P-d3bPIdJYebw0Tw=w408-h271-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.1693094, lon: -75.5960834 },
    createdBy: null,
  },
  {
    id: "dogshit-spot",
    name: "DOGSHIT SPOT",
    city: "Berlin",
    citySlug: "berlin",
    address: "Marchlewskistraße, Friedrichshain, Berlin, Germany",
    types: ["ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmXZL4nlbdktuu36oj0NWlwUZ-3AZtagRffI6f1El85ViWZpGeH3Axn2OflYtsnwU03bVHcRuJcGIOixJvvrz0DAyL2A5UVAdfeI7rd3O4V7UpSSN3oZGe0w3_bfSBxgFFFW9jr7Q=w408-h306-k-no",
    country: "Germany",
    countryCode: "DE",
    location: { lat: 52.5076013, lon: 13.4488483 },
    createdBy: null,
  },
  {
    id: "place-louis-pradel",
    name: "PLACE LOUIS PRADEL",
    city: "Lyon",
    citySlug: "lyon",
    address: "Place Louis Pradel, Lyon, France",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmogi9H-3aA-N8Dab_TnEA06ixOyxx5V6pG1z_3fWMoLxxVQ0_ZAn7iqK2rjrams1VHTpXu0hlt2bjKVcgfi2CmLpGfNRTmUQF5dvrU1OIVCn5AXepMT85nfpKTWzPZJDnYHlT7=w408-h423-k-no",
    country: "France",
    countryCode: "FR",
    location: { lat: 45.768613, lon: 4.8369251 },
    createdBy: null,
  },
  {
    id: "bercy-skatepark",
    name: "BERCY SKATEPARK",
    city: "Paris",
    citySlug: "paris",
    address: "Quai de Bercy, Paris 12e Arrondissement, France",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkJs9fMgLOhFethwr7LIbdUWXY_chOezSkG97A17i1L0P0ZwLxqxMPXXOG3XnSpXvFBV9DiAnNv0A2JmeRAvIsnSIKcnz6WsTCnQND6kbhWABpiAiJuBUI7HzzH0uu6BnSnDRESVw=w408-h306-k-no",
    country: "France",
    countryCode: "FR",
    location: { lat: 48.8373219, lon: 2.3789662 },
    createdBy: null,
  },
  {
    id: "skatepark-de-la-4-sur",
    name: "SKATEPARK DE LA 4 SUR",
    city: "Medellin",
    citySlug: "medellin",
    address: "Comuna 15 - Guayabal",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkSLCc-vwYNx2Cg8bbWQxf31i5U9qtL7ZXcqTZOCoVGjNrlXD5JQSKePVCww_g6Q-sAQ1CG8Zpd1He8R9JodXvoFY4BuhSKHXPitdd32ODmNyfYcMgnpLDFf0uaxOZKvhUyM1vJ=w408-h306-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.2047065, lon: -75.5798671 },
    createdBy: null,
  },
  {
    id: "skatepark-zipaquira",
    name: "SKATEPARK ZIPAQUIRA",
    city: "Zipaquira",
    citySlug: "zipaquira",
    address: "Carrera 15",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk9ADVee7kMaxVWbSqroQ8OIMC_4DT5G1yrnOBxdPACYsC21dnQpHpdr3IpJO6nnFdVaIr0A2HmPA-yn5wGSfg5brvCcz4ysjXxMuZB371pQJKlc-AKDKfufGMgDKXflYK2JSv3=w408-h306-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 5.020761, lon: -73.9999073 },
    createdBy: null,
  },
  {
    id: "skatepark-ponte-della-musica",
    name: "SKATEPARK PONTE DELLA MUSICA",
    city: "Rome",
    citySlug: "rome",
    address: "Ponte della Musica, Flaminio",
    types: ["diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk5RgCYmVBj45UgNe1F5gY-F_wGVQiYdkJneacp-u52jJortCxSFIKVKSBf3Z7UA68Au3xEQ0RetT7-1PCE-PBis5JwhdowP5ZVPFoGlDe5aiI7Ur6T5LjdiaDT9zHShVXSAqIB=w408-h725-k-no",
    country: "Italy",
    countryCode: "IT",
    location: { lat: 41.9266668, lon: 12.4604421 },
    createdBy: null,
  },
  {
    id: "skatepark-tep-emile-lepeu",
    name: "SKATEPARK TEP ÉMILE LEPEU",
    city: "Paris",
    citySlug: "paris",
    address:
      "Rue Émile Lepeu, Quartier de la Roquette, Paris 11e Arrondissement",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmrm6RZMyRGW6wbRVxMg5ZTL-8cIL0EzXkrqq9Yn0UjBJxYBlUwRHRut-JXRiNv1gIvwI4iyXqX8Eg-OgQdAP-RS6yGELOn2LaH7WCvf61n-tqr9KbAEmgHydVOzdZKgOlTJ5mu=w408-h306-k-no",
    country: "France",
    countryCode: "FR",
    location: { lat: 48.8563378, lon: 2.3884269 },
    createdBy: null,
  },
  {
    id: "planet-park",
    name: "PLANET PARK",
    city: "Tokyo",
    citySlug: "tokyo",
    address: "Japan, 〒650-0011 1746-1 Tobukimachi, Hachioji",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk14M2Md5BBEeBf4KHx0Q8j-cypuOr1fgZHZjymHyxboyF9M2KnGXETBxVTkG_sDmTe2FqJw1IG--Qb7EKM5zsyMxuCMs06l3Q2BrlmakBJtJ1p0IX8p60GKU_gBIGJumWxkguuiQ=w408-h306-k-no",
    country: "Japan",
    countryCode: "JP",
    location: { lat: 35.7132208, lon: 139.2898981 },
    createdBy: null,
  },
  {
    id: "parque-linear-aguas-do-camanducaia",
    name: "PARQUE LINEAR AGUAS DO CAMANDUCAIA",
    city: "Amparo",
    citySlug: "amparo",
    address: "Av. Dr. Carlos Burgos, 1967 - Jardim Italia, Amparo",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkXe1dtM6iN_JFLg3amnbDM9_89p-QZm94iA_Mvyj1FkOQB_YmkMvY8xLhb3Tp5KBJT_O6IojgU5rqCfuKFj7HgHZIg-6vIUkOQAL0M2KNrWefGorDdboscyvdBW54ug6bpF5k6=w408-h306-k-no",
    country: "Brazil",
    countryCode: "BR",
    location: { lat: -22.7031789, lon: -46.7721865 },
    createdBy: null,
  },
  {
    id: "parque-das-aguas-amparo-bmx-skt-park",
    name: "PARQUE DAS ÁGUAS- AMPARO BMX & SKT PARK",
    city: "Amparo",
    citySlug: "amparo",
    address: "Rod. Eng. Constâncio Cintra - Amparo",
    types: ["plaza", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnhEi4FOw0D7AEN1QfWjDOTxjDpxwediKujGKiw3m0teDaQZUNR3nTFx7ZYnntbHkfiPKWeOXGI4dUw6org4__RLVmHg40hwnyEPuVrvpXRizFmYDGeiWxZ2ZrKabRBD8jhfn4=w408-h506-k-no",
    country: "Brazil",
    countryCode: "BR",
    location: { lat: -22.7366186, lon: -46.7636622 },
    createdBy: null,
  },
  {
    id: "japon-diy",
    name: "JAPÓN DIY",
    city: "Bogota",
    citySlug: "bogota",
    address: "Al lado de la Registraduria de Kennedy",
    types: ["diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnyZQUp_davM3Jp6oxynqRFlcVyczKo85UVpz6Eg8J1PIwat3JLpZp021YJsCQvQq2F6j-J3_CUOqBmYNeYJ-4EQ7OcezqtaVCOsg-4LVSOjNYsI_wimxoj6O2E48xhJDmcJ4kG=w408-h279-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.6204317, lon: -74.15473 },
    createdBy: null,
  },
  {
    id: "skatepark-de-pineda-de-mar",
    name: "SKATEPARK DE PINEDA DE MAR",
    city: "Pineda de Mar",
    citySlug: "pineda-de-mar",
    address: "Rambla de Catalunya",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlGUzY6RqvTHXRXxcEL8UjfWeU6QDSw5oNXkAT3b48LT_80i5kI7uLIdzyfNNbwh8uL8d-isilMilAEtsVToCNw4xJWC6Zs_zJtTs0Q-zwmx7k1feNfXoqbVMjJbk0gRyyZHspEXA=w408-h306-k-no",
    country: "Spain",
    countryCode: "ES",
    location: { lat: 41.6227554, lon: 2.6835812 },
    createdBy: null,
  },
  {
    id: "phillips-diy",
    name: "PHILLIPS DIY",
    city: "Bogota",
    citySlug: "bogota",
    address: "Puente Aranda",
    types: ["diy", "plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkFjvmAmzHIMqzz1v1WqabCHO_aGINc7PiSy10SovC_04suQKMtF3h_zOZlZTfY26-F_wYK5wK_yacRXzYZtWLFzL-TyvvVZveDDEj-paZTFqVBJhU3TAVJHzfzNHbG9GYPqYj5Bg=w408-h306-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.6457122, lon: -74.1111908 },
    createdBy: null,
  },
  {
    id: "san-antonio-de-prado-parque-de-las-ruedas",
    name: "SAN ANTONIO DE PRADO PARQUE DE LAS RUEDAS",
    city: "Medellin",
    citySlug: "medellin",
    address: "Calle 50E Sur, San Antonio de Prado",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmTDHMcG3jmUT4m42sFg6JmjITkgcvC4wYCgbNruXUfDsLyBtbtrxt4nC7X5Kiz1IkCNpkStj5BvnuGnaAzDD7sHAo9PdDeRrLFU-O2O1NS3VYpAbZ5ML-78-oIp8PAirOqXaA=w408-h306-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.1768804, lon: -75.6550942 },
    createdBy: null,
  },
  {
    id: "skatepark-mar-bella",
    name: "SKATEPARK MAR BELLA",
    city: "Barcelona",
    citySlug: "barcelona",
    address: "Av. del Litoral, 106, Sant Martí",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkGPvU2xQHxb06Gj49PG3BUKxDREzuOD-yPWFHDpe2rOya1Yn3pKlLG6Ie3OEcU-3EfWG2N4wMCqyF2hODbjif20xfbZQ5J102f3Tc5HJTFa-x0q4mnhMkO1h8JFMVQ6hMcTc5O=w408-h306-k-no",
    country: "Spain",
    countryCode: "ES",
    location: { lat: 41.4014705, lon: 2.2106526 },
    createdBy: null,
  },
  {
    id: "skatepark-la-marina",
    name: "SKATEPARK LA MARINA",
    city: "Barcelona",
    citySlug: "barcelona",
    address: "Pg. de la Zona Franca, 99, Sants-Montjuïc",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmpBklYpzALi_kbD1HBVDtLPB6yxLcY0BUjjiv6BsbJQdh1VPneIikrtVM2mMwqUeYpMzI8yPugbEprXTXEVSV_BAqiYdQMGxZJLAF16IL15AQSTjRCOPAlrEuWHoiKJq56I13hpdoGVgiv=w408-h281-k-no",

    country: "Spain",
    countryCode: "ES",
    location: { lat: 41.3611693, lon: 2.1383742 },
    createdBy: null,
  },
  {
    id: "shinyokohama-park",
    name: "SHINYOKOHAMA PARK",
    city: "Yokohama",
    citySlug: "yokohama",
    address: "3300 Kozukuecho, Kohoku Ward",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlKlC7NrN24HWbxcFG6hwSfNbYeEzsgTX5u7Hz3PuDo_DZL1GaOzmKST5g9_CIpGHcpddBXf0wTJNLKfdIDlb76KNDr1P2EeeRZdJe8sB-QlQ0pAEgSQsAjEGZ_oBUGmPJ67Day=w408-h306-k-no",
    country: "Japan",
    countryCode: "JP",
    location: { lat: 35.53123537787763, lon: 139.59813765034306 },
    createdBy: null,
  },
  {
    id: "hangang-ichon-skate-park",
    name: "HANGANG ICHON SKATE PARK",
    city: "Seoul",
    citySlug: "seoul",
    address: "370-2 Ichon-dong, Yongsan District",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWndS57dFsyFr-qcEh2QUy6MkxWVZk2LKAR2EbLyluFyoMAfq_t7fNwGEl1G4zsRvlHvJRDTOQ9OiJAc9hIJNkiRo5V3qMZEX8_i5qe9Du44a_nUDJOGra8dLNUtrhiBLa4ecmZ3=w408-h306-k-no",

    country: "South Korea",
    countryCode: "KR",
    location: { lat: 37.5241302, lon: 126.9662873 },
    createdBy: null,
  },
  {
    id: "picnic-diy",
    name: "PICNIC DIY",
    city: "Barcelona",
    citySlug: "barcelona",
    address: "Carrer de Carmen Amaya, 16, Sant Martí",
    types: ["diy", "plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/APNQkAESTNQ2DplJPHJFJi-7DnlnBNuScv2YvgiPxzbp7pLHr3EdrFaSLtetHYP_qU4ovs0rv_YHqhPr1c9jb6a52TGumBcZhwYnB9ChddNeldBMuOmb_PnquDiIiW_o0QDrDxGS6l-9ig=w408-h544-k-no",

    country: "Spain",
    countryCode: "ES",
    location: { lat: 41.3948025, lon: 2.2039027 },
    createdBy: null,
  },
  {
    id: "skatepark-sopo",
    name: "SKATEPARK SOPÓ",
    city: "Sopo",
    citySlug: "sopo",
    address: "Calle 3 Sur",
    types: ["bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnwWHtxjkIPFt_9hreni9VdsUGpAKeYwq8OSalHjcSQqZhJRRBjBLnZSkyFzUJ_1WFCQ0p4r8TXvD3_wus7fByy3PwpeYbhCpbPaecZ4_oUbKAfYDyAIIA_0LgEnNQFH1En6qCo=w426-h240-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.9068944, lon: -73.944922 },
    createdBy: null,
  },
  {
    id: "suvilahti-diy",
    name: "SUVILAHTI DIY",
    city: "Helsinki",
    citySlug: "helsinki",
    address: "Kaasutehtaankatu 1",
    types: ["diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlNuvPAeiWDXBboqEaaLvd9j1cYuwnDbuy7AyfGbaSQN2v-uq9C056dje1leW6Yl6n6UcbB0aHef9Nzy46x9_4NZvR6B9-MR-ZwIkAQ-6xeSE_r-4Y6z2Mm8Sg0JgqntQQPjQVS=w408-h306-k-no",

    country: "Finland",
    countryCode: "FI",
    location: { lat: 60.1914641, lon: 24.9762351 },
    createdBy: null,
  },
  {
    id: "skatepark-rabat",
    name: "SKATEPARK RABAT",
    city: "Rabat",
    citySlug: "rabat",
    address: "X4W9+9X4",
    types: ["skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkwoa2rSDiBA1t379tUDqdFG0t2L8uGGM7W94U7AhqzX1W5HUP16j4BSYHEHIQ6NYPHBkFbLKonKgPO0XW4lYZYqerMIp8zgz3Tqan8bcfd_7585JaTeuXv5Hxzo2SQRc9faRdkWA=w408-h725-k-no",

    country: "Morocco",
    countryCode: "MA",
    location: { lat: 31.1728205, lon: -7.3362482 },
    createdBy: null,
  },
  {
    id: "skateboard-park-malabata",
    name: "SKATEBOARD PARK MALABATA",
    city: "Tangier",
    citySlug: "tangier",
    address: "Q6JJ+PC8",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkxJq1o16max3s8l2kLnypit4Qr4MK_5WE-ExklW_2zvhna4vN3QjS72Xt5JkyyBYemfhWlrv_EFLhpurdqOoYFS0oJ8CldKkGKH3g_djvZFRolTxbrwrrQESurWGsuOBQKzqN2=w408-h306-k-no",

    country: "Morocco",
    countryCode: "MA",
    location: { lat: 31.1761139, lon: -7.3389063 },
    createdBy: null,
  },
  {
    id: "place-nevada",
    name: "PLACE NEVADA",
    city: "Casablanca",
    citySlug: "casablanca",
    address: "Casablanca 20250",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWko5pYyodzE3Fxa6HcIQtyoj_jmftZcHEwlUL0-L03wUqll2H-XdozT5aP1v3ejLycyoWg0Bikz_kv9twvuM6hon8ej2gfJbzxrMmsov5K_jfRwKTsF3f0byAMjlQZCLxmry5ir=w408-h306-k-no",

    country: "Morocco",
    countryCode: "MA",
    location: { lat: 31.1728205, lon: -7.3362482 },
    createdBy: null,
  },
  {
    id: "skatepark-taghazout",
    name: "SKATEPARK TAGHAZOUT",
    city: "Ida Ou Guelloul",
    citySlug: "ida-ou-guelloul",
    address: "Taghazout Scatepark, N1",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnbMIbOLgzM0UHsXMahPr5EQLp0orpJahUbAoQjaxah-R1ciq1hJQjUT1dU7lzya4IZ49JLi-UVniEj7Eg_EkvxA1vSiKcMYIH4vYn5o64exq9twEs5J7rpEJQ0_nkTT7sIyJUWEQ=w408-h272-k-no",

    country: "Morocco",
    countryCode: "MA",
    location: { lat: 30.549154774618263, lon: -9.713136232693822 },
    createdBy: null,
  },
  {
    id: "bab-ezzouar-park",
    name: "BAB EZZOUAR PARK",
    city: "Algiers",
    citySlug: "algiers",
    address: "20 rue hachemi ourabah",
    types: ["skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm-nWWH4spJV8RKvg3iXimavNJbstfjPtDH4lE2wWldDQLKcTy_Dnq9tFmBFnK78QWixl-GasbdrehxwTGExmP6dmMUBAxgmELf9ZaiiTSwnaAGdWn7P1LeQ9lQo-NNYmZ1hwW_=w408-h271-k-no",

    country: "Algeria",
    countryCode: "DZ",
    location: { lat: 36.7177532, lon: 3.2011865 },
    createdBy: null,
  },
  {
    id: "skatepark-el-hamma",
    name: "SKATEPARK EL HAMMA",
    city: "Algiers",
    citySlug: "algiers",
    address: "P3XC+Q88",
    types: ["plaza", "skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn2XvdddRQfDDj-sV_5gVLZw05be57sdd9xKemhpCPbIbLZONR2_uNNyw9J5XzQvqn8iar29g00AYO7TULkLpZ6qAzU6GQLrlJbKXow8Zve-6YnJcxXINcOXyX5i52ePM86RMUZ94gERmvE=w408-h544-k-no",

    country: "Algeria",
    countryCode: "DZ",
    location: { lat: 36.7509652, lon: 3.0715274 },
    createdBy: null,
  },
  {
    id: "egy-skatepark",
    name: "EGY SKATEPARK",
    city: "Giza",
    citySlug: "giza",
    address: "Waslt dahshur road",
    types: ["ledges", "skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmlHVklj1XNEQXXIxGwDn1hBeyTZEuWhOFEnBj4WhPlxIIYLfNvS-5FW6MTkGKQh-XSsrF07ZajW2bStBx7WaPqEzp3VaZQAXXCc8LItx40gQ5BHT6p_mcYOyo-qqr2DVHIlPZTPw=w408-h306-k-no",

    country: "Egypt",
    countryCode: "EG",
    location: { lat: 30.0503301, lon: 30.994742 },
    createdBy: null,
  },
  {
    id: "suli-skatepark",
    name: "SULI SKATEPARK",
    city: "Sulaymaniyah",
    citySlug: "sulaymaniyah",
    address: "Hawary Shar",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm2qeup5aCFLilz1KSCKWt87A0boW5mYOcfokb7OXKe142Dx2gkG3JLQoI8h5RE2fEk0GTkJXuM5Mu6SZrPlqqZisn0lWoH1kcTWcjHtaR0XW54Q6p1k0VnhY93tX2aBFFFXMY=w438-h240-k-no",

    country: "Iraq",
    countryCode: "IQ",
    location: { lat: 35.6218139, lon: 45.4324519 },
    createdBy: null,
  },
  {
    id: "bakhtiari-suli-skatepark",
    name: "BAKHTIARI SULI SKATEPARK",
    city: "Sulaymaniyah",
    citySlug: "sulaymaniyah",
    address: "Youth Center, Near, Bakhtiari Kon St",
    types: ["diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlqWqNlHR0PXbz_pPxwuNHK3iiM2R8CKHKEb8pxscmN3BlpCSccxUrUlcKPzAxi_DVZ2QbY7xb-j35sW9GNSYGtT9VAvUp8ZAwNje9ofRGriPQo1eWCbIzfeEAh-B7UEbt4lmvVnA=w408-h544-k-no",

    country: "Iraq",
    countryCode: "IQ",
    location: { lat: 35.5779535, lon: 45.4018951 },
    createdBy: null,
  },
  {
    id: "galit-park",
    name: "GALIT PARK",
    city: "Tel Aviv",
    citySlug: "tel-aviv",
    address: "Tel Aviv-Yafo",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnGZwCBKiCDz-FLsvgj2iKWRyFVNkcd7g9kfmKb9RnXBI68JgzajjxnWMZDlQZgnbEVmi7wNuL1d5L0R2_9JDUdEW08_0DVEkEWl24E3WfLKKb3g0K-AIe_EHsN4QqMuviqy9N7tA=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 32.079432, lon: 34.776592 },
    createdBy: null,
  },
  {
    id: "skatepark",
    name: "SKATEPARK",
    city: "Modi'in",
    citySlug: "modi-in",
    address: "Modi'in-Maccabim-Re'ut",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn3ZrSOOhEyxTPDdeckVwFPEIe7FhZu5i7uit3ZlcV7wV0jQpljh48Aum3o7BJ4CYigH33-978RsxRsBQ3Tla9VhewQpOL7yoLslfCcthUrG527eo_wyQblpRznEQO7p-WHSI0T=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 31.9262114, lon: 35.0001726 },
    createdBy: null,
  },
  {
    id: "tel-aviv-skatepark",
    name: "TEL AVIV SKATEPARK",
    city: "Tel Aviv",
    citySlug: "tel-aviv",
    address: "Wingate St 2, Tel Aviv-Yafo",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgPkNO4trgWQ8xW9VeTbS7cWDh6ELL-eHuQI4iJxk5WJ4LajAq1IQ9fiYlNUTugESyfWdQP4KBM5ZzVSEFHhjdwPBUktRXoX_VwmoBCl3nbFJnPXhS6Y9kScNZGjcYVumHa3Ll=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 32.0615602, lon: 34.787325 },
    createdBy: null,
  },
  {
    id: "skatepark-nahariyya",
    name: "SKATEPARK NAHARIYYA",
    city: "Nahariya",
    citySlug: "nahariya",
    address: "Shvil David Dadon 15",
    types: ["bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmMcpbq0LQAmCorpSdhQ0QM0ROQ3E2uDKiuAOnw02Gma5aNgSB9lGp5ZU0Iai6GZt9qaB0kxF5Kd9I5Cpd8PndQhyLfypQfUt3JvDqpQnRDlM9aLES0MgWTMk3A3sdoDLZfuGyI=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 33.0075648, lon: 35.0892883 },
    createdBy: null,
  },
  {
    id: "skatepark-rishon-lezion",
    name: "SKATEPARK RISHON LEZION",
    city: "Rishon LeZion",
    citySlug: "rishon-lezion",
    address: "Herzl St 136",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnlt16HwUxHth5oFjY1jqZP3PAaCW6MBkDrQmWMWVQ_MRcWP5NB7XKByZ0Qg0B-oawesw7qlJQCa2zCUAF_TLrr8V06zuj3rmvFZWUGMJGUM-Kqzncui8Ft68x0CGaFpW9uIbA=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 31.9551982, lon: 34.8016161 },
    createdBy: null,
  },
  {
    id: "skatepark-of-haifa",
    name: "SKATEPARK OF HAIFA",
    city: "Haifa",
    citySlug: "haifa",
    address: "haifa",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkDInDkNC4cPY1ZxV9z3UtIH8hRJYhKr-gsS7O0krWmBg7aKykZdU42UgWAt0FXkVmQkO42HH9Z4yULCTfBu7iFymr92YLyG0mu4unKSb3D4BDYyyCkRyx0y7PD4YuJaJRpo7iM6A=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 32.8125893, lon: 34.9627496 },
    createdBy: null,
  },
  {
    id: "skatepark-in-ashdod-yam",
    name: "SKATEPARK IN ASHDOD YAM",
    city: "Ashdod",
    citySlug: "ashdod",
    address: "Sderot Moshe Dayan",
    types: ["ledges", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkZrGtH5fVn7D46Xs9VhLr3GXVgaIZRQ_evrvHJNgK58gc3nu4q-VTcBFnFmrMS23V-SLo8nt5RGrjxncM8JIDCX9TDhci9Kmu4WXGwrsBN32gOM0GAOaA_irBtReSuLiwl3plxPA=w408-h306-k-no",

    country: "Israel",
    countryCode: "IL",
    location: { lat: 31.8391524, lon: 34.6535811 },
    createdBy: null,
  },
  {
    id: "the-i2b-somerset-west-skatepark",
    name: "THE I2B SOMERSET WEST SKATEPARK",
    city: "Somerset West",
    citySlug: "somerset-west",
    address: "Lourensford Rd, Somerset West, Cape Town, 7130",
    types: ["skatepark", "ledges", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkIE-dYyF-WohZzWS-5iaeUKlPA7waqlomGCNYpkfxnzOBdmcEGg8Sj9-SADNWKpFE4qKGBW-gTxNFsT1ERY6GqgDQ9iGIojuGh_owuaQob9G7gwT6vuj4I-lWFWjqS_25YjE1I=w408-h306-k-no",

    country: "South Africa",
    countryCode: "ZA",
    location: { lat: -34.0406154, lon: 18.8687686 },
    createdBy: null,
  },
  {
    id: "west-green-spine-skatepark",
    name: "WEST GREEN SPINE - SKATEPARK",
    city: "Ar Rayyan",
    citySlug: "ar-rayyan",
    address: "8C7H+827",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmYYjSxA4QlahHmHsea6jGmdGwNrTFkMzebZ1nSQAvBQJ31w9xM-6SGVGTwHIwphbzw8KRvlLZlVXIrwzcI_W4-DNEp7Mk5tIhlAg6qxtkyRuJzmLzxC2JoExG2-cu-79Y__d--nw=w408-h306-k-no",

    country: "Qatar",
    countryCode: "QA",
    location: { lat: 25.3411888, lon: 51.4362787 },
    createdBy: null,
  },
  {
    id: "meadowbank-skatepark",
    name: "MEADOWBANK SKATEPARK",
    city: "Sydney",
    citySlug: "sydney",
    address: "Constitution Rd, Meadowbank",
    types: ["skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWknjcYpEC8TsyJS0pIXpaiGAwBvV3qvvB7ua7hVGmSshY5KLZ7vxahD1WjgJJR5ZF3gjpI2EG6LcUnZ2UAraHUeL_SpU2Jp77sqo2ws5AMM3uArbVPyKokhylHkGAbRBDQGctt4=w408-h272-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -33.812496, lon: 151.084335 },
    createdBy: null,
  },
  {
    id: "skate-park-battery-park",
    name: "SKATE PARK @ BATTERY PARK",
    city: "Cape Town",
    citySlug: "cape-town",
    address: "Victoria & Alfred Waterfront, Cape Town, 8001",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmVZaeyrgZRS5O5pW-E21c9z0NCG9M4XwZQQcUcaZ4V4lU-HHaRzGnNBUdP9GHvdmgYyNXAj0JsppGyJGkd9qAYLmCzKCBX9ltZ7Pp40zEgkELEzJ7cjIW_ELqC97-rlhIzNISd=w408-h306-k-no",

    country: "South Africa",
    countryCode: "ZA",
    location: { lat: -33.904802, lon: 18.4219093 },
    createdBy: null,
  },
  {
    id: "the-shred-skatepark",
    name: "THE SHRED SKATEPARK",
    city: "Milnerton",
    citySlug: "milnerton",
    address: "Lagoon Gate Drive",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlJHLERnEaXaToow0mwIA9ofOL5tYfZMrXDPAhan1d1vpxn6YhKPDOaHDDpzVeoQ79GjmL9RixseaenwTRClhCb3QfuID0DeajX-AYh88LBOxcmj2GEh85BgcuSOALxYUN89Y77zQ=w426-h240-k-no",

    country: "South Africa",
    countryCode: "ZA",
    location: { lat: -33.8948256, lon: 18.4802951 },
    createdBy: null,
  },
  {
    id: "thrashers-padel-skate",
    name: "THRASHERS PADEL & SKATE",
    city: "Pretoria",
    citySlug: "pretoria",
    address: "241 Serene St, Garsfontein",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm-kpeIL0DB-u7oZyyLrBIMUwRVd-Q7aYt0xUKHrX9zkjUf5jXktx7Af97IUo4YKRC_nUXFR9uduX2A7pe-cjVt9NfmKa0piOwkQh_OxfataNg4ho-GFLBK5OPzZP3mzUe5DXhj=w408-h305-k-no",

    country: "South Africa",
    countryCode: "ZA",
    location: { lat: -25.7813952, lon: 28.2862223 },
    createdBy: null,
  },
  {
    id: "gsx-skatepark",
    name: "GSX SKATEPARK",
    city: "Hammam Sousse",
    citySlug: "hammam-sousse",
    address: "Complexe Sportif",
    types: ["skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmMUnUmhdMaEcnoHRXTMlXYnFUXKEa4NB7jDZPFxVvBrqBA4fajwWkfE6ejxA7_bZ4UFRmfMVnEgvWJtM06VdwmwqWPvVdyk-KzUm5NPWE-B8uqno9JkcgTgNaRVPmQ1G_eE817SQ=w669-h240-k-no",

    country: "Tunisia",
    countryCode: "TN",
    location: { lat: 33.8439408, lon: 9.400138 },
    createdBy: null,
  },
  {
    id: "la-marsa-beach-skatepark",
    name: "LA MARSA BEACH SKATEPARK",
    city: "La Marsa",
    citySlug: "la-marsa",
    address: "V8PJ+FFQ, Av. Habib Bourguiba",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmVwy-n2R-ABd0P8FwbO0HJr3FDp6ibxMNgtzMVJK-DhudVOgQxQiL6PyNkW4BzH65oVue5kKvHjnyhdpgEeAJfMIo7Y88Ec_rT4g_GX27KCE4qBjvmIigvI5Y3ea1ARSUyDxY=w408-h677-k-no",

    country: "Tunisia",
    countryCode: "TN",
    location: { lat: 36.8899452, lon: 10.3256976 },
    createdBy: null,
  },
  {
    id: "msida-skatepark",
    name: "MSIDA SKATEPARK",
    city: "Msida",
    citySlug: "msida",
    address: "Triq il-Ħida",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkGLc5qkLLlo8OvuCHAsfoGwHT4xUjnZlfads6c4qkWlFMxz-Xr0Fuf1LIP-RzEJuku5olPzrDHhi5TPnRMmmVQXi70cJZc0qX4NedFUcZt4RLrG6X_6Y_Bt7xAGuAtMHj1WFiQ=w408-h306-k-no",

    country: "Malta",
    countryCode: "MT",
    location: { lat: 35.9079565, lon: 14.4820671 },
    createdBy: null,
  },
  {
    id: "sydney-park",
    name: "SYDNEY PARK",
    city: "Sydney",
    citySlug: "sydney",
    address: "Sydney Park Rd, Erskineville NSW 2043",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnlyfKD-6pCvnKKI0G4MaLNL1IK0kQ9ZbEmnaoTwftlyzIIuQYsxXpsyVnZKpjYNgmFDERoxZ8Y58ZvJZwu93XraxECWMBts0kCdTVdDkU5AEn0HoXuaPPsWB1sp25tOmeepP5k=w408-h306-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -33.8875632, lon: 151.1869484 },
    createdBy: null,
  },
  {
    id: "bondi-skatepark",
    name: "BONDI SKATEPARK",
    city: "Sydney",
    citySlug: "sydney",
    address: "102 Campbell Parade, Bondi Beach",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmiAqAwzWtXtaU1Uf24YRS35l3l4DoEPHkT78aTq2_q82tSNHjwzOVFx0onrGzfIKYQp1r9kz1KpuiQECKtFKkhqO3MY8rhhSgCpW1lFFhIURoOTzFMmado7GtalzLp18PVHHDM0v7xRyUS=w408-h544-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -33.8899111, lon: 151.2741124 },
    createdBy: null,
  },
  {
    id: "south-eveleigh-skatepark",
    name: "SOUTH EVELEIGH SKATEPARK",
    city: "Sydney",
    citySlug: "sydney",
    address: "39B Henderson Rd, Eveleigh",
    types: ["skatepark", "plaza", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnHNse1V_7Imv-94hYvqqpzCgTTDv8PAodXQuDO4WJO_g8m4rFKwsFGu0xl9u2eSkbRO8sL_RqbZfK5DDu_pQ05vxx5NyMxwBGoHB8MCsL1af4DRx5ZAuQ74IY1SbWBG_-OVORoxg=w408-h272-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -33.8949046, lon: 151.1947706 },
    createdBy: null,
  },
  {
    id: "st-kilda-skatepark",
    name: "ST KILDA SKATEPARK",
    city: "Melbourne",
    citySlug: "melbourne",
    address: "Marine Parade, St Kilda VIC 3182",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnoTo9DEe2OEHu9laLysbWq8cY3h6j9pZpUZb2B_C0cYZGsjNYgdasGzdNA5A3ELP-YjLeigqJXpH5MKKGkJ_y39UGZYVyQPy96UqP90h4ZpdF1GU41T9q5qXcyAMnn7cSFKsXPXL2kJ48=w426-h240-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -37.8700324, lon: 144.9758406 },
    createdBy: null,
  },
  {
    id: "box-hill-skatepark",
    name: "BOX HILL SKATEPARK",
    city: "Melbourne",
    citySlug: "melbourne",
    address: "Canterbury Rd & Middleborough Rd, Box Hill South VIC 3128",
    types: ["skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnyzS9dqR3UvTcvnFea_KwKTVmxGW6FXnKkPdP1ZBYaz3kNB7fgrQlo7UpfMe-QELBJOeSvU_W0TVE-8hIY9SEcMl2rqkyJUZfbh-JqeX1xf2zAqzSyQPouDrmzUGGHunomcEDORIgN2lw=w408-h306-k-no",

    country: "Australia",
    countryCode: "AU",
    location: { lat: -37.811553, lon: 145.1309284 },
    createdBy: null,
  },
  {
    id: "valonia-skatepark",
    name: "VALONIA SKATEPARK",
    city: "Hibiscus Coast",
    citySlug: "hibiscus-coast",
    address: "2 Valonia Street, New Windsor",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnaOEFv_beHDHifV_itNETw-rxzREK9tp84GsXpJCnwIgInapwVEzkZgwHFYcbR-XX3nhhAlkduMNLHGWzWzI5DapPJ7zsoEyPsaX4lPGA7CEsjSq6oGKWfZ89B-sBco9cHQzSJQQ=w408-h306-k-no",

    country: "New Zealand",
    countryCode: "NZ",
    location: { lat: -36.717312, lon: 174.7426508 },
    createdBy: null,
  },
  {
    id: "marlborough-skatepark",
    name: "MARLBOROUGH SKATEPARK",
    city: "Auckland",
    citySlug: "auckland",
    address: "Archers Road, Glenfield",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlk7JOdouelqPVyeR15I8KqTZLdcRXnt2FJZ6ZT6yAqzfEgrr_e8KK6ycn-Pz0H1icPhDzaHWrf31ZLcMyG6Ev0gksV0YDG3piGTr24NVcq62eV-tQ5BKfllAptPxzbOm97WC5xkJ56Nac=w408-h306-k-no",

    country: "New Zealand",
    countryCode: "NZ",
    location: { lat: -36.7604866, lon: 174.7401101 },
    createdBy: null,
  },
  {
    id: "low-park-suba",
    name: "LOW PARK SUBA",
    city: "Bogota",
    citySlug: "bogota",
    address: "Suba",
    types: ["diy", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWntj_BLyIaRP9zhzYdB9Wd5zsxQ-efGpIZFn7ls7XJpE9NUOQinzCdQnoTYt-PVyhmMnBtIJaQQweG_rF0vHg4fHDHTunfX9ILcds8ZDdV316dhngQF5ITURtH8Bo1Ik8eI2S5YRQ=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.7441627, lon: -74.1117833 },
    createdBy: null,
  },
  {
    id: "fontanar-skatepark",
    name: "FONTANAR SKATEPARK",
    city: "Bogota",
    citySlug: "bogota",
    address: "Parque Metropolitano Suba Fontanar",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlLd70Wnd3k0L0qdOHXyfW3mGmL7-mYZ84SpGGH5jW17MjX56ujsiV6KKCoPjh17pqQMGvNsdwYPrnwPZNDfRrDwAi5R4t5WM6qLnSADL1NgaOs-6yNZOwc00QhhS-5KJB36_iLHQ=w426-h240-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.7569629, lon: -74.1110535 },
    createdBy: null,
  },
  {
    id: "tercer-milenio",
    name: "TERCER MILENIO",
    city: "Bogota",
    citySlug: "bogota",
    address: "Avenida Calle 6 con 10",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkoAw0S5PT6sCKD_Sxe6KDyaLdFfL3cOu-DjORhTOwMtpfDoxTXZJ6y23p-PQm52B6YtdEOExqsGDIAKmwZFzn7FbWBNSzXVzHuslawrBGsyx64cNhyleTzKm9giLHT8WoKsoxm=w408-h272-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.5961163, lon: -74.0818412 },
    createdBy: null,
  },
  {
    id: "vigas",
    name: "VIGAS",
    city: "Envigado",
    citySlug: "envigado",
    address: "Avenida las vegas",
    types: ["skatepark", "stair", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm4UAzCEpvojpbRBBcIi9t8SVhsPKzr2Op9QMP7SlESY-xcMmgRat86emoYxRleLuC1u2Bqrw5T6ads_3UVIZETE8eyS3AcMpAD4lryzSYPoEoPONLad4WJ9y5mJbNe-bN88ITAtA=w408-h271-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.1693094, lon: -75.5960834 },
    createdBy: null,
  },
  {
    id: "madre-laura",
    name: "MADRE LAURA",
    city: "Medellin",
    citySlug: "medellin",
    address: "Puente de la madre Laura en Castilla",
    types: ["skatepark", "stair"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkxJ4CkPNO2uwwc4rXP90Za-cMucGUkbUD53Wr1sUci2e3_T4P5eS8kZtOPDFUs3NF7xK3qZr1mfwOMtsJLnc_4eWfau-SmKmcNImjb4Sx4xyBjLazLQH1KmSZEDRTx63yCgf0Q=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.2872832, lon: -75.5670802 },
    createdBy: null,
  },
  {
    id: "skatepark-rionegro",
    name: "SKATEPARK RIONEGRO",
    city: "Rionegro",
    citySlug: "rionegro",
    address: "Parqueadero Unidad Deportiva",
    types: ["bowl", "skatepark", "stair", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkbNIg-w604XEwW5M6j7ap_LXP-VH-aCsNi8JwQoRMmuA01zH2cpfVik9gyTYcq9e_lI4X_izBWEK6zCt6q9kQFvtnSfxAf3m2RNLPMjTwXEQNQulOiYqPYMaYqqe-SPW8nNbTp=w408-h408-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.1476343, lon: -75.3736431 },
    createdBy: null,
  },
  {
    id: "niquia-skate-plaza",
    name: "NIQUÍA SKATE PLAZA",
    city: "Bello",
    citySlug: "bello",
    address: "Plaza Norte Centro deportivo Tulio Ospina",
    types: ["plaza", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnIectgBaDK8_rSHObKmH_bWBOufLzZ8TKSeTQLq2bDe8UXt1v7R34-Y0VpBiZv2eHFN1vBb-oiCmUITfXyRyASoyHhwWG9HWnFb7tIhGr8zu3djpXJ5ORX2hysTGnsYBeEHUc=w408-h544-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.3359596, lon: -75.5458352 },
    createdBy: null,
  },
  {
    id: "skatepark-estadio",
    name: "SKATEPARK ESTADIO",
    city: "Medellin",
    citySlug: "medellin",
    address: "Laureles - Estadio Metropolitano",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7GtFITlk6-vqWHXJRtQuqatDpAvzpxFCModqGOLtpUUmVaSs9iFfMhnhUFfVjCqbSwRpzwngqglGjTRH7IWwfCy069b4nlgoT3ORGZev0GFwll7PA9E8G7meldSVnc9hF5V8=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.2544093, lon: -75.5885225 },
    createdBy: null,
  },
  {
    id: "la-pinuela",
    name: "LA PIÑUELA",
    city: "Medellin",
    citySlug: "medellin",
    address: "Aranjuez",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlv6PMtBG4HScBxXx4ZHose5OT2PP1CaKE3T4SAbRA3Zd21m7iZmHmCybEoIeTpKyuccu85fKXirx8HgaoNLnHyF9ULCSiToeGmaqXrt6V-1zgbW0b75ZpJLVhb6GhQ1p59mmZ4KQ=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.2786432, lon: -75.5572487 },
    createdBy: null,
  },
  {
    id: "bowl-ciudad-del-rio",
    name: "BOWL CIUDAD DEL RÍO",
    city: "Medellin",
    citySlug: "medellin",
    address: "Parque de ciudad del río",
    types: ["bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnnHGcY11KeGZOdMDGicXTalUt-G0YGs8dXvesddHlevuq1kT5Nu_1fXNHvRcTbVm9U6Fsqrey1vTbDQR_BQlxXum_YKx0tmENrNiCz-Uq2eWKxn1VuGKMsyBnez-PxaTsaUGg=w408-h725-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 6.221283, lon: -75.573225 },
    createdBy: null,
  },
  {
    id: "skatepark-la-villa",
    name: "SKATEPARK LA VILLA",
    city: "Pereira",
    citySlug: "pereira",
    address: "Villa Olimpica",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmQPo6bbFX1tZWGxgZJOQRd5ry5uwhpIwkHu2rFc-C6bHqW00yo-k9LYN8MUhanuEjgqVIJ3XzHFw1mxb6Nbw13sV6aLdxxZRjf-TR2topzAWXplWTP26Q2n-PpZDUI0P2htw=w408-h247-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.8103242, lon: -75.7521167 },
    createdBy: null,
  },
  {
    id: "calida",
    name: "CALIDA",
    city: "Cali",
    citySlug: "cali",
    address: "Carrera 52, Unidad Deportiva Alberto Galindo",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmHGNlrEM2_caiHMx0_IZNAIFxUqbJePSBk1PgwoQe_i4tiyDz3bS8_YOvWe3SHCx274iYeCj6QGl-o7Bciflf4rd62GC3Gpx88xVFgBbUd7_GawOBdJiCNSdSt7KaBvhocq2_n=w427-h240-k-no",
    country: "Colombia",
    countryCode: "CO",
    location: { lat: 3.4147268, lon: -76.5523151 },
    createdBy: null,
  },
  {
    id: "parque-venezuela",
    name: "PARQUE VENEZUELA",
    city: "Barranquilla",
    citySlug: "barranquilla",
    address: "Parque Venezuela",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnp36Y1O2fsRKyDisJXQqg7cjSR25pgrJXswzyPC-yMtfsNWp8ZA6oGjd1J_Lhw5Cy_p1oBnr7Srn0fIeZw-iPeIvGrYuO5eoT3VrZcRMlYe3Ob1TFiSadmYkML6V6xP3TM951L=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 11.0015935, lon: -74.8241558 },
    createdBy: null,
  },
  {
    id: "malecon-del-rio",
    name: "MALECÓN DEL RIO",
    city: "Barranquilla",
    citySlug: "barranquilla",
    address: "Malecon",
    types: ["skatepark", "ledges", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQ-Wa1RIEfYI5IWH3Qgrz8FINkAjxv1eRmjyQyhXaOBYBgLBVW8xB8G3HR8XugFg2HQKN_nMLkJaoe4gjWpxFbpUpaN8aKqHwFbea7mzh8Of5yKvaAcSRZA_c2f_YADx8YTATZcGoq_Ts=w408-h540-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 11.0093384, lon: -74.7814371 },
    createdBy: null,
  },
  {
    id: "el-obelisco-plaza-de-la-paz",
    name: "EL OBELISCO - PLAZA DE LA PAZ",
    city: "Barranquilla",
    citySlug: "barranquilla",
    address: "Plaza de la Paz",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWld6KOO0sJktsWDixTPB_nUeL0-FuJ_1PU7p52K0QWqPsahAdEJux-iB7wm3G64lhZzKxCxoMI96p3Fme3QhO_aFr2FIZlcIEMhGLxPpypco8WTb0XBzmAzyDeYvl-D5FcyQD-7=w533-h240-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 10.9882502, lon: -74.7871201 },
    createdBy: null,
  },
  {
    id: "entrepot",
    name: "ENTREPOT",
    city: "Brugge",
    citySlug: "brugge",
    address: "Openbaar Entrepot voor de Kunsten",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkvp26KPfgasHlcGq_zfGUCpIb513o2Nv78r_sd7nhka6NLocKl1Ic7tNOhrGmLNL1xsKhsWfhJLXzkyN3HWRPXYlFltDRWp3q-ANCRXs67Cmqq3_zdnURZPJxm2WT2fr54SYQ6=w408-h725-k-no",

    country: "Belgium",
    countryCode: "BE",
    location: { lat: 51.2269593, lon: 3.2257727 },
    createdBy: null,
  },
  {
    id: "olympiaplein",
    name: "OLYMPIAPLEIN",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Olympiaplein, 1076",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm8cvL2yiCJbGZXdjS3Fvc-GIXGrQ4QxcANastTVAY9_LGR0X7Rq1pjk4intBcFza9l-8IoTayH2zyih_P4ekzSKBth0aCkCf6tynWyAOQxeXDGaSIhakFTrjMIyjDtuAPROZUk=w426-h240-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3507636, lon: 4.8692369 },
    createdBy: null,
  },
  {
    id: "noord",
    name: "NOORD",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Aambeeldstraat 38",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm4ntjuGkHpu-HUFSUDD0qOdMWrZLEKE-D58QvR6PJaiUzPNGoMo9xz9YVB7qTfz0WudwG5ayVbTbmTt6EfSA5T6SJybpYZMhoBfekEY-VsEEF64lm5n5SBvxxJjG26-aGDwdeiDA=w408-h306-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3871086, lon: 4.930037 },
    createdBy: null,
  },
  {
    id: "urban-sport-zone",
    name: "URBAN SPORT ZONE",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Eef Kamerbeekstraat 43",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmo49BrHcREAyvnLD5fIOwq84FSZlrqwe00Lk9qxZWqQ2DRzPUZwyKR6JRj4akZba-b4ZL62-QHpx-IHSSj3aLqt515nJnhF0dGbUjAXNA2ppWb2pnryg-Eozcx5F6wsNXMX4U=w408-h271-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3788936, lon: 4.9627664 },
    createdBy: null,
  },
  {
    id: "museumplein",
    name: "MUSEUMPLEIN",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Johannes Vermeerstraat 7",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkVgARVuEwCzi5IUVkUysMUKuB0fi-ryAYX-RZMQLS1VLyBdEkXtPpY1P14eGtS-RoD_pBQkmhJY4luknqKyiF5lMi9EjgxAv0qPPlP2Pqy_mTJ37nwZEAaJ6lAgmN1QEuFqmWtifO8kxuc=w408-h272-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3628668, lon: 4.8851569 },
    createdBy: null,
  },
  {
    id: "marnix-bowl",
    name: "MARNIX BOWL",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Marnixstraat 44",
    types: ["bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmRAvfZNrplBLqKZnDBzfeNha4bjqH450OEek4kC5_4mIV1sZbP4y_sxwX33dCdOsM38614zCh5oJIt6yaNNV_QK6Wzcj0HFJR-LmHZULOV_2MPWWByBYUdT34riSmD9QD3mGIUMQ=w408-h306-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3859632, lon: 4.8804949 },
    createdBy: null,
  },
  {
    id: "zeeburgereiland",
    name: "ZEEBURGEREILAND",
    city: "Amsterdam",
    citySlug: "amsterdam",
    address: "Eef Kamerbeekstraat 43",
    types: ["skatepark", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnN1sSzUo5ioFyIFWzSOZln_b8gyse34PFt040YCr-vT5JCS5dFw40sQS9WBCmFbelhrJRHCJRuTxTagQFAghe4BKSE3FSOIR-hLZ8JxpfTxtWWEPi5wk77_d3AtAmN_lqDpgZGqQ=w408-h306-k-no",

    country: "Netherlands",
    countryCode: "NL",
    location: { lat: 52.3786968, lon: 4.9672289 },
    createdBy: null,
  },
  {
    id: "skatepark-mosquera",
    name: "SKATEPARK MOSQUERA",
    city: "Mosquera",
    citySlug: "mosquera",
    address: "Mosquera, Cundinamarca",
    types: ["skatepark", "ledges", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWljwWIunGSY5LvEHFGKlJuABC6c4Xs_xn3AL_94275CBrOwnKhhrqZ22bKKqBZaUYKuQf7gBZy5s2VNVcg9YIXhbp-rRdzwLHP_3bdrVNE-z3eWMvZWN0J7rMQr9Fp42wCMnzcS=w408-h306-k-no",

    country: "Colombia",
    countryCode: "CO",
    location: { lat: 4.7125141, lon: -74.2304501 },
    createdBy: null,
  },
  {
    id: "blu-enigma-andros-hotel",
    name: "BLU ENIGMA - ANDROS HOTEL",
    city: "Andros",
    citySlug: "andros",
    address: "Apikia, Andros 845 00",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-proxy/ALd4DhHXAuArgrObhIjPXbMlAY1A8_Jgr2Nl6-V_as2NmIVS8Zsf4Egacy9CySe-vbQAbpFteOS3-OVmKv5BVnurgc0-QW7DsVIy0c1mlXqWEylwYU74_fJhy3fImXvlSMUMkhNBR_5jbZISb48j73Ss7fOjzqBdvkcJyipoT1_jnlBfczEuNyilVCFTiw=w423-h240-k-no",

    country: "Greece",
    countryCode: "GR",
    location: { lat: 37.850643, lon: 24.9099218 },
    createdBy: null,
  },
  {
    id: "vagapark",
    name: "VAGAPARK",
    city: "Zaragoza",
    citySlug: "zaragoza",
    address: "Ronda Hispanidad",
    types: ["diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnNi-aCqAJarvmRdX5jYVhP4nCamIvX29vv8MV-jnqorJVqyRmhVOogdpBbJzpbmECtuOAJhpL2nLuJC0pnp52vc0QY5APYGU9WUKKIkZ7QW_4nodyJBPKkTukleqJeipyHau5IG-vfsUY=w408-h544-k-no",

    country: "Spain",
    countryCode: "ES",
    location: { lat: 41.6306384, lon: -0.8651181 },
    createdBy: null,
  },
  {
    id: "gsf-skatepark",
    name: "GSF SKATEPARK",
    city: "Oslo",
    citySlug: "oslo",
    address: "St. Halvards gate 1B",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnppnKdgzf1LVh8tOILB712N5ow9JOGafkITs5kw4-CtGC0jH9LIMrmr_51UjadSxAsYbUFqe3vz2sIgSz2QmA5lSo7IWlH7JzFjOJZzcZ_CMMJ4eRyoE1cPN43d-kT84mXT7mj=w408-h306-k-no",

    country: "Norway",
    countryCode: "NO",
    location: { lat: 60.0975535, lon: 10.7595171 },
    createdBy: null,
  },
  {
    id: "tasta-skate-park",
    name: "TASTA SKATE PARK",
    city: "Stavanger",
    citySlug: "stavanger",
    address: "Gjerdeveien 30",
    types: ["bowl", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnVreLSJn3uZGNcpJijtmkz_XFQFn5M7KeQdk49HrI5YdZPXS7xWhJmLBHEq8P8NB6kDaoSRqltEnWpHDUEgwMfuKSPHODW6RH_WzFFFWUhLNYBSBK0gfIHn46HM9sLCf_8dicv=w408-h260-k-no",

    country: "Norway",
    countryCode: "NO",
    location: { lat: 59.2012045, lon: 5.8023297 },
    createdBy: null,
  },
  {
    id: "highvalley-skateworld",
    name: "HIGHVALLEY SKATEWORLD",
    city: "Vallentuna",
    citySlug: "vallentuna",
    address: "Magelungsvägen 169, 124 58 Bandhagen",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkgnk27hMWfdnVzMgHB1L_SkcW4a3P_DSxynznhCXNcx6mDWTLWTlvq64hjvZx_fuJTeGep5B_bEveUyj5x2e2s3ibsI6876_nBh-HZZEILAykzoIO8k8ceKZSEHF8RP1j8YBxx=w408-h284-k-no",

    country: "Sweden",
    countryCode: "SE",
    location: { lat: 59.5846496, lon: 18.1513895 },
    createdBy: null,
  },
  {
    id: "stapelbaddsparken-skatepark",
    name: "STAPELBÄDDSPARKEN SKATEPARK",
    city: "Bjuv",
    citySlug: "bjuv",
    address: "Stapelbäddsgatan 3, 211 75 Malmö",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmOPu5VJ_a5Rtks5xemEw8MdqhQ2SL3ZNrTdEaS5UfKw6Z0edWuGfLY7dKSpQKC-khPzHb9MpVv6rTBxLmS2UE7YW47kiTATl8C1fhq9wh3_QIXPmmr3rH_0-XYL_07JqAKf8I=w408-h306-k-no",

    country: "Sweden",
    countryCode: "SE",
    location: { lat: 56.1014772, lon: 13.0063443 },
    createdBy: null,
  },
  {
    id: "action-park",
    name: "ACTION PARK",
    city: "Gothenburg",
    citySlug: "gothenburg",
    address: "Burgårdsparken 1, 411 40 Göteborg",
    types: ["skatepark", "ledges", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmCuKmMjUS1HwIoqYtC-T8-qKy7eFmZWDdr9MoBRYMpFBG_FmVlyCBvCJwRUwb970vK0XPRqF8aqZEhpDvcI4vgylCRwXpeHFNbkHjeODZ5rLR9C1GZXC_DOQDqvcyde7Vxt0aX=w408-h306-k-no",

    country: "Sweden",
    countryCode: "SE",
    location: { lat: 58.1315173, lon: 12.1737111 },
    createdBy: null,
  },
  {
    id: "halmstad-arena-skatepark",
    name: "HALMSTAD ARENA SKATEPARK",
    city: "Halmstad",
    citySlug: "halmstad",
    address: "Växjövägen, 302 53 Halmstad",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkDpE2LTi-0l9W5dkDZ31f4VAd8Z4ZSErzepjrkRzh8O4CZJa_VsVpi4YM-a5pIdqOog3Go72stwgDJZb0i5ZbM6Ay2SD4L8UFzEtIQG0iLfWKoHfitYsUTgQQDMN0VVAC7CbySGg=w408-h408-k-no",

    country: "Sweden",
    countryCode: "SE",
    location: { lat: 57.1829393, lon: 13.1075346 },
    createdBy: null,
  },
  {
    id: "ralis-skateboardpark-rs",
    name: "RÅLIS SKATEBOARDPARK [RS]",
    city: "Stockholm",
    citySlug: "stockholm",
    address: "112 35 Stockholm",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmWyagBihDbxUFtl8MN1UhBjAcBkYPicHTkkj7qRgEG_9brM9fNU4eVU_a80NL3ACPPNTQ2NkcGaiJR03Z_A7XB1YVd7vVNsQcOkvSufix-dPBO5IgqO1JD6jY9q5Ict6Tq8od4=w408-h544-k-no",

    country: "Sweden",
    countryCode: "SE",
    location: { lat: 59.7433354, lon: 18.1062014 },
    createdBy: null,
  },
  {
    id: "flipside-skatepark",
    name: "FLIPSIDE SKATEPARK",
    city: "Flekkefjord",
    citySlug: "flekkefjord",
    address: "Flyplassveien 156",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk1X6zDv5wenyybGGbZMCE-nlfKzEkAZK1E6QH-_HWDEJ36ql0JUJVXPBguhOiRnaaybrH27DJXKpUmrpkszaeWoC9NEk-GnHVMlqNCjUuEGYqeCNLWnr5O5VWpQO87-hBpvCB8Sg=w408-h544-k-no",

    country: "Norway",
    countryCode: "NO",
    location: { lat: 58.3260516, lon: 6.5726602 },
    createdBy: null,
  },
  {
    id: "oslo-skatehall",
    name: "OSLO SKATEHALL",
    city: "Oslo",
    citySlug: "oslo",
    address: "Stavangergata 28, 0467 Oslo",
    types: ["bowl", "ledges", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmV70nzl1a15FM-Nd60h6F1o-ILA_Hj5cOQ7GtNsWyFZ6vQvWhMcPO-6g0MLDxp1JrJ0Q3duo1uzi8MVa_cfVy2fT9Zg_MzOVCzSnAv6GcguhRFTwmGE2zCJGXUOiIpqtzlig5U=w408-h305-k-no",

    country: "Norway",
    countryCode: "NO",
    location: { lat: 60.1112227, lon: 10.7673917 },
    createdBy: null,
  },
  {
    id: "brettafelag-reykjavikur",
    name: "BRETTAFÉLAG REYKJAVIKUR",
    city: "Reykjavik",
    citySlug: "reykjavik",
    address: "Dugguvogur 48, 104 Reykjavík, Iceland",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkfcOo1AE7_-tISxlcIWLSyTr2X4T3EaemwRDkTtebjud_1eoEEfLBX7WV9nq7DPGK8YOcBy98cb8oFm4nxdUNwfSiIO1nV1_QEj0T3ZTSIsHQU2dLsPKhu7eKLMi7Jru6Sa-C45_cxhkz8=w408-h307-k-no",

    country: "Iceland",
    countryCode: "IS",
    location: { lat: 64.2089874, lon: -21.822363 },
    createdBy: null,
  },
  {
    id: "braggaparki-skatepark",
    name: "BRAGGAPARKIÐ SKATEPARK",
    city: "Akureyri",
    citySlug: "akureyri",
    address: "Laufásgata 1, 600 Akureyri",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWma94-6V2DVozY1QfJnOSS80n55PiSUMSPzlhVV7BWE8uGPTlonXXprG1SsKYO3jr6vdE8BuCwqI54rIs5l7ZDuDEsqyAE7Z7VcD9EZa7ClBsYn7zZfgyWBHVs24lQs3X4-CQYk=w408-h272-k-no",

    country: "Iceland",
    countryCode: "IS",
    location: { lat: 65.7458544, lon: -18.082973 },
    createdBy: null,
  },
  {
    id: "f-lledparken-skate-park",
    name: "FÆLLEDPARKEN SKATE PARK",
    city: "Copenhagen",
    citySlug: "copenhagen",
    address: "Edel Sauntes Allé 3, 2100 København",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkzv623o0zBvi8I4D5qd_wRWPnHK4nVNAfCy_mhXrcTvPAQ4QXkvKWOGaPHxEOVSQQRcvZK_KLgSjfUOCZkYkkYDMFuMBp0i6pDTxNL2RCOvcImpg48fgOZgWJLCwSMMJgTFJg=w408-h306-k-no",

    country: "Denmark",
    countryCode: "DK",
    location: { lat: 55.76658, lon: 12.556738 },
    createdBy: null,
  },
  {
    id: "ashbridge-bay-skatepark",
    name: "ASHBRIDGE BAY SKATEPARK",
    city: "Toronto",
    citySlug: "toronto",
    address: "Coxwell & Lakeshore Blvd. East, 1420 Lake Shore Blvd E",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm4hoARKhYwmpSeaX7dhDqau_KczJp3JJIK1n6GZ12Iwh10rI235F8-PBs8BnW2AsgXl7tvvTU_-702YPqAJUkl8bp_7_UrOBElZ_AyXb1-zXaP7F7c-5FFawYx6qK7-xM3R7ZGhQ=w408-h306-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 43.671097, lon: -79.3102557 },
    createdBy: null,
  },
  {
    id: "underpass-skatepark",
    name: "UNDERPASS SKATEPARK",
    city: "Toronto",
    citySlug: "toronto",
    address: "Lower River Street, Toronto, ON M5A 0T4, Canada",
    types: ["ledges", "plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWleBDkOGGITngv8zuWBjkcSQzsp0QbO96V0xsZdOXPB_POyTTMTKceXi7JYAAZrDktTnJxaf4rGsgezB6wx7AHx_BijMzvJkZ7jpKvSRCmlikCgoPksIDuMoMMUeg9PU-yHvOavwA=w426-h240-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 43.6669651, lon: -79.3566195 },
    createdBy: null,
  },
  {
    id: "vanderhoof-skatepark",
    name: "VANDERHOOF SKATEPARK",
    city: "Toronto",
    citySlug: "toronto",
    address: "60 Research Rd, East York",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnGHjObQ0vAw0h0AaLmwJdICAtbCGo0bWUqT8WFEZHNff3rnpWKeUov0qldxnYY4BhTMojq6KeQ28vnuilXlSgXGNOoPtOX__n7qOiPVeT6fRN1rny3HbcLLbi1VsWLLiOBGVKG=w408-h306-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 43.7226242, lon: -79.3514604 },
    createdBy: null,
  },
  {
    id: "jordon-carter-memorial-park",
    name: "JORDON CARTER MEMORIAL PARK",
    city: "Toronto",
    citySlug: "toronto",
    address: "160 Eighth St, Etobicoke, ON M8V 3C6, Canada",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmWuiTspZZD4lC8wkIQPQOJne3J5ziOutDW6dYd6N6a7IKSf0b6fADBhh12Qx8IaCm3lwndqgOoSeLapiyVKZwi4ZLMV68NnugbnSyNOJtxGMyz2HC8JY_JKdJAGFaxTQff8PCn_Q=w408-h306-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 43.61227, lon: -79.50391 },
    createdBy: null,
  },
  {
    id: "van-horne-skatepark",
    name: "VAN HORNE SKATEPARK",
    city: "Montreal",
    citySlug: "montreal",
    address: "5855 Boul. Saint-Laurent",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlXfYij0Jxl_JnABBUNjBx2ZLG-qSKdZEzutGWUar3NmLuubGcqbYT92NXIX_VH2mUi6XfJ1-UxmYnYaBGq2ilMjGSR5_dg_tx0EY30mNgQSmyMMFZRtUp3hunD-dr4lUETtu_mjw=w408-h272-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 45.5377329, lon: -73.6007009 },
    createdBy: null,
  },
  {
    id: "cj-s-skatepark",
    name: "CJ'S SKATEPARK",
    city: "Mississauga",
    citySlug: "mississauga",
    address: "560 Hensall Cir, Mississauga",
    types: ["bowl", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkloLFam1FdsIZED4bHe0nanFPpYO32A3R5hvnOVWApNm8S01IxTOoWybpaYsI5oplzvDihnb1vrHCvPav5mEiocSa1pkik6ggt4wIUK94CJNOdKIvN8uGa5PcM7QK7PjdKL3WC=w408-h272-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 43.5990884, lon: -79.6016972 },
    createdBy: null,
  },
  {
    id: "banff-skateboard-park",
    name: "BANFF SKATEBOARD PARK",
    city: "Banff",
    citySlug: "banff",
    address: "Sundance Rd",
    types: ["bowl", "ledges", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl-QFwTf6js1sQCh-zD8AGn2CT3bZ9herOIV_uhzAKOrt0KpxQGH-qeVA83BctWpETV3AfcqKRBPA6i5IKvAwxGqZwsm_loWPG7q3AyAbjjEERB8DexXD2saMU_6jEeRB7LXcQ=w408-h306-k-no",

    country: "Canada",
    countryCode: "CA",
    location: { lat: 51.1828128, lon: -115.5774637 },
    createdBy: null,
  },
  {
    id: "venice-skatepark",
    name: "VENICE SKATEPARK",
    city: "Los Angeles",
    citySlug: "los-angeles",
    address: "1800 Ocean Front Walk, Venice, CA 90291",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlXZBMB2bk7v5zGO3Hxfxqh181TFvUsRWecMeQLx3e8tk5xLy7_BAc4S2UL3zBDu5xrPYKTen40Vptz3CwDcu0yJAeRZWu1G8T0DCLJHo_1Yg3S8aPs1e6RDFqUu_vOh3H0KJov=w427-h240-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 33.9917625, lon: -118.4757346 },
    createdBy: null,
  },
  {
    id: "vans-off-the-wall-skatepark",
    name: "VANS OFF THE WALL SKATEPARK",
    city: "Westminster",
    citySlug: "westminster",
    address: "7471 Center Ave, Huntington Beach, CA 92647",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlTVD2n0qSt0-7zg_CN-TKoHyPwVF8qwZLd0oPlTxtgd2wFKfB8Ath6p6J_xN-PMDB4oz0IqamlnWATVtH23Wo3eVYyd3DosNyw8IICIkkPcrtZ32ODS5bEBvNOiZsLbV69NgI=w408-h306-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 33.7470129, lon: -117.9973677 },
    createdBy: null,
  },
  {
    id: "les-coleman-skatepark",
    name: "LES COLEMAN SKATEPARK",
    city: "New York",
    citySlug: "new-york",
    address: "62 Monroe St &, Pike St, New York, NY 10002",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlLQqYSGw9LB4KYT0ubHkWLATWNEcT-WU50O3_2pk1f1i3w0_V8ss6lKA8FjFQ2kVhEKDC7_SdXjO90eqBfZG8Nb6G6I_uo0frB5h_TnUMuxUX7jhbke6pGsRJxqMG8R4EEMTwZ=w408-h272-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 40.7220909, lon: -73.9929628 },
    createdBy: null,
  },
  {
    id: "brooklyn-banks",
    name: "BROOKLYN BANKS",
    city: "New York",
    citySlug: "new-york",
    address: "355-365 Pearl St, New York, NY 10038",
    types: ["plaza", "ledges", "stair", "diy"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnktHH7rHXUcGLmiwmbo-mk7lbugGhcCGwGp5IgJPrVWBRO66Hlf318EJVcwXAAR3TX-BByyddDKGk19-wMhwCO0T_-ES1s9N4Sl9WSoJmYp-iyP0Ccq-z4NDzrlTSmkxvZXQ4MDQ=w408-h306-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 40.7196499, lon: -74.0028575 },
    createdBy: null,
  },
  {
    id: "maloof-skate-park",
    name: "MALOOF SKATE PARK",
    city: "New York",
    citySlug: "new-york",
    address: "Astral Fountain Flushing Meadows Corona Park, Corona, NY 11368",
    types: ["plaza", "skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlRFAuxOEifxfkm4l66klkov2eN9y8yHWaZIiKg5V9Sm77HdxPKYRR80GgpdM2Swak4mqc5F7QMM_ccokRsCtMozfWcCziy3sF7rkUVlyD_FR2dqxOL7k3htN7edsIf7VRfmvzivw=w408-h272-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 40.7538715, lon: -73.8459965 },
    createdBy: null,
  },
  {
    id: "desert-breeze-park-skatepark",
    name: "DESERT BREEZE PARK SKATEPARK",
    city: "Las Vegas",
    citySlug: "las-vegas",
    address: "8425 Spring Mountain Rd, NV 89147",
    types: ["skatepark", "ledges", "bowl"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkMpEnfkXMayo-evLerDdsuGpLUFM5weIrIV3_69ZIGr1Hv6xHQcxHrNoMF9nRb7xDxH2P6gryzuigt_RD8pm4lAy8k_ghozBfhCIGIkbVrOrSQKeMbD627541u2ueXjRrNGa3p=w408-h306-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 36.135144, lon: -115.270325 },
    createdBy: null,
  },
  {
    id: "craig-ranch-skatepark",
    name: "CRAIG RANCH SKATEPARK",
    city: "North Las Vegas",
    citySlug: "north-las-vegas",
    address: "628 W Craig Rd, North Las Vegas, NV 89032",
    types: ["plaza"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn9AuHi8cVc3PKP_AhIwfkzI4hbiFzb6CR73yKHwAic6HtI0_gugzweYcYFpHn7xJwIO_Q9Z8TeH2ShZHk2CKx5ebm56yjpRze50jehTw_vHPoyqSLFYZGC3DBv9C38TeJYvKrmoNVB3YuG=w408-h272-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 36.2521372, lon: -115.1562681 },
    createdBy: null,
  },
  {
    id: "durango-skatepark",
    name: "DURANGO SKATEPARK",
    city: "Las Vegas",
    citySlug: "las-vegas",
    address: "3521 N Durango Dr, Las Vegas, NV 89129",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkHYto4KOlO0X70AnNNnYWnFmV-9rrWZCLQKtCSA_TH3Ifqd99w8f5g5rkZMg3m8Vg6EEwyoL3Po7gJYR_hsdCsi0ZG1dnlr0qAldUiaDNQercfqtrF4PfbW-KHdkUvDwhVZwFk=w408-h544-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 36.2361615, lon: -115.2819299 },
    createdBy: null,
  },
  {
    id: "duck-creek-park-skatepark",
    name: "DUCK CREEK PARK SKATEPARK",
    city: "Las Vegas",
    citySlug: "las-vegas",
    address: "8699 Park Villa St, Las Vegas, NV 89123",
    types: ["skatepark", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk4XPqwtMaFw1hdz63xGCJhbGeUPtEvq0f3zvi9QN-QT_ioVgp18WexVd0jXXwa9WKFpi-1r8-yxNNam7FRNRSkBV_hnO22zi8qDuFmHZ5cZ3spDtx2uZu2QWFuYgQviOwhzA=w408-h306-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 36.045374, lon: -115.137463 },
    createdBy: null,
  },
  {
    id: "hollywood-regional-park-skatepark",
    name: "HOLLYWOOD REGIONAL PARK SKATEPARK",
    city: "Las Vegas",
    citySlug: "las-vegas",
    address: "1650 S Hollywood Blvd, Las Vegas, NV 89142",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnL_gWSWEsoZmKhV1ChsmWNzTzlBbjhx8qK6cWimwtXDmQWM1fbiNRaChsKL6JDv1bhymvGKLWKUH7vbiQsfBAjIhX14isrPAADZ-g0OwCMYz1avitQ8tPYL-3wSObm9QHWuxvY=w408-h306-k-no",

    country: "United States",
    countryCode: "US",
    location: { lat: 36.165138, lon: -115.03276 },
    createdBy: null,
  },
  {
    id: "skate-park-constituyentes",
    name: "SKATE PARK CONSTITUYENTES",
    city: "Mexico City",
    citySlug: "mexico-city",
    address:
      "Av. de los Compositores 1505, Bosque de Chapultepec II Secc, Miguel Hidalgo",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlbGgOqbL01EGPYRyR8Cgwm55EzrDiTlWNY5JFI3kN9AwfYF9yg4G7BvXHElpPMIoHxk6f8R4eCYkA2a9qpwooqRtC0IhWA8lKaNeVebeEwIPqgRQAlZHq0tjFrrXF8a1PU0uI=w408-h272-k-no",

    country: "Mexico",
    countryCode: "MX",
    location: { lat: 19.4334312, lon: -99.1949419 },
    createdBy: null,
  },
  {
    id: "skatepark-bosque-de-san-juan-de-aragon",
    name: "SKATEPARK BOSQUE DE SAN JUAN DE ARAGON",
    city: "Mexico City",
    citySlug: "mexico-city",
    address: "Bosques de Aragon, Gustavo A. Madero",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWktJ_HW66X5VeeXPcRj38MqQmruU6qXHoy6_N6s8xAtptHjkLmx6Tk7FEwxNm3Lp-C0R4hLGXvmCMr0-91z0ADGrji5XqGLi-Y_EDHkFybA52khj5Q9MjH45LbOmwKetBFTJhKy=w408-h306-k-no",

    country: "Mexico",
    countryCode: "MX",
    location: { lat: 19.4887611, lon: -99.0729512 },
    createdBy: null,
  },
  {
    id: "skatepark-planta-de-asfalto",
    name: "SKATEPARK PLANTA DE ASFALTO",
    city: "Mexico City",
    citySlug: "mexico-city",
    address: "Unnamed Road, Ajusco, Coyoacán",
    types: ["skatepark", "bowl", "ledges"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnlmGl4QP5fhNkK4p3Euxgek7XBYelxYwwwNrtsqY8dRB_zBZebpIgJYVCxJpO1uVWcSKsFAR4U_RF7oDyOXvsk4Y4vDdaULS9LkJ-YLGWtlhCUox-7z97_rSJ6VnNmWDBpLU-qcA=w408-h408-k-no",

    country: "Mexico",
    countryCode: "MX",
    location: { lat: 19.3337029, lon: -99.1675296 },
    createdBy: null,
  },
  {
    id: "skatepark-los-coyotes",
    name: "SKATEPARK LOS COYOTES",
    city: "Mexico City",
    citySlug: "mexico-city",
    address: "Av. la Virgen, Coapa, Ex-Ejido de San Pablo Tepetlapa, Coyoacán",
    types: ["ledges", "skatepark"],
    sports: [...SKATE],
    image:
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlJk23D7ot5si3TP2jtiWmUisHGoY8_exgoguvuidJn2NlYe97C_DZ_12pE0U4xAH8iqnxg32f84UAYc3RFt8mBxo3ZLfEI6KKcAQ3zgYriYF1X00CHmdQEzuFVFiMSzx3CSzIUAMy2TkA=w426-h240-k-no",

    country: "Mexico",
    countryCode: "MX",
    location: { lat: 19.3345745, lon: -99.1248382 },
    createdBy: null,
  },
];
